baseURL: "https://krishnakattiyan.github.io/" 
title: Krishna Ramamoorthy
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Biography
          url: biography/
          weight: 1 
        - name: WIN Lab
          url: winlab/
          weight: 2
        - name: Publications
          url: papers/
          weight: 3
        - name: Teaching
          url: courses/
          weight: 4
        - name: Senior Design
          url: design/
          weight: 5
        - name: Archive
          url: archive/
          weight: 6
params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs."
    author: Krishna Ramamoorthy
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Krishna Ramamoorthy"
          subtitle: "
          Hi! I’m an Assistant Professor of Computer Science and Engineering and director of the Wireless Intelligent Networks Lab at Santa Clara University.
          <br><br>

          <p><strong>Office:</strong> Bergin 204</p>
          <p><strong>Lab:</strong> Heafey 165</p>
          500 El Camino Real, Santa Clara, California   <br>
      

          <br> <p><strong>Email:</strong> kkattiyanramamoorthy[at]scu[dot]edu</p>

          <br>

          If you’re exploring new research directions or just want to bounce around ideas, I’m always up for a good conversation and a meaningful collaboration."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Biography
              url: biography/
            - name: WIN Lab
              url: winlab/
            - name: Publications
              url: papers/
            - name: Teaching
              url: courses/
            - name: Senior Design
              url: design/
            - name: Archive
              url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: KrishnaRamamoorthyCV.pdf
        - name: LinkedIn
          url: https://www.linkedin.com/in/krishnakattiyan/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=mpyQj0cAAAAJ&hl=en
        - name: ORCID
          url: https://orcid.org/0000-0002-6248-4739
        - name: Email
          url: mailto:kkattiyanramamoorthy@scu.edu
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: GitHub
        #  url: https://github.com/pmichaillat
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Krishna Ramamoorthy"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
